### ISSUE TITLE
Create Table for Suppliers

### ISSUE THREAD

**Issue by EthanDRaymond** [ryanabury/CMPSC431W_SP17_Project#3]
A supplier is a person or company with at least one product listing on the site.
Each entry will have the following attributes:
1. Company Name
2. Address
3. Password
4. Point of Contact
5. Email
6. Phone Number
7. Company Category
8. Yearly Revenue
9. Company Profile Page

The profile page includes:
- Profile banner (optional)
- ‘About’ section (optional)
- Rating info (average rating, recent comments)

![image](https://cloud.githubusercontent.com/assets/4635266/23270685/a72864c2-f9c2-11e6-8bd2-154a209c28d0.png)

**Comment by cpdcode** [comment]
I uploaded suppliers.sql to the sql directory. I think I got everything that you listed @EthanDRaymond

**Comment by EthanDRaymond** [comment]
@cpdcode Looks Good. Closing Issue
