### ISSUE TITLE
Create Table for Registered Users

### ISSUE THREAD

**Issue by EthanDRaymond** [ryanabury/CMPSC431W_SP17_Project#4]
Non-registered users cannot bid, sell, or rate suppliers, users, or items. To register,
a user provides a:
- Unique username
- Unique email
- Password

The username must be unique so that users can hold each other accountable. The
password must be at least 8 characters and contain at least one number, and one
symbol. Users log into their account using their email and password.

Before bidding or selling, a user must finish setting up their account by providing:
- Full name (first name, last name)
- Postal address (street address, city, state, zip code)
- Credit card info (credit card type, number, CVV, expiration date)
- Phone
- Age
- Gender
- Annual income

A user can edit their account settings, but previous constraints still hold. A user can
also have more than one address and credit card.
Registered users are given a profile page that includes:
- Username
- Profile picture (optional)
- ‘About’ section (optional)
- Rating info
-- average rating
-- recent comments

Users can customize their ‘About’ section and profile picture, but username and
rating info will be shown by default.

![image](https://cloud.githubusercontent.com/assets/4635266/23270761/f05623fa-f9c2-11e6-92f3-ab25b498ebdc.png)

**Comment by c-dougherty** [comment]
The reg_user SQL file and tables should be in their final form. Closing this and creating new issue to verify running SQL file creates intended tables.
