### ISSUE TITLE
Item Page [Beautification]

### ISSUE THREAD

**Issue by EthanDRaymond** [ryanabury/CMPSC431W_SP17_Project#65]
Waiting for #60 #61 

This is a page for a single item. It must list all of the information for that item.

Must include information including, but not limited to, Sale information, rating information, seller information, bidding information, and delivery information.

**Comment by ryanabury** [comment]
Basic implementation is complete. Waiting to beautify.

**Comment by ryanabury** [comment]
Buy an item
