### ISSUE TITLE
Main View

### ISSUE THREAD

**Issue by ryanabury** [ryanabury/CMPSC431W_SP17_Project#68]
Combine all elements (header, footer, navigation bar) to allow seamless use when creating other webpages rather than having to implement all separately. This will reduce the possibility of error in creating webpages as well as making the entire process easier. 
Example here: https://j2html.com/examples.html

**Comment by EthanDRaymond** [comment]
@ryanabury I did what I think you mean here https://github.com/ryanabury/CMPSC431W_SP17_Project/pull/77
