### ISSUE TITLE
Create Table For Sales

### ISSUE THREAD

**Issue by EthanDRaymond** [ryanabury/CMPSC431W_SP17_Project#7]
Transaction data will need to be stored to keep records of sales. In this
circumstance, sales refers to any purchase that is not done through bidding for the
item. A sale is completed for a publically listed amount. If an item is not currently
available, an order may be placed and the transaction will be fulfilled when the item
is back in stock. Each transaction will need to store the following attributes:
1. Buyer ID
2. Item ID(s)
3. Seller ID
4. Credit Card Number
5. Sale price
6. Transaction Status
7. Transaction Completion Date

After the sale is successfully completed, the item is shipped to the buyer and the
transaction record will be maintained for at least 6 months.

![image](https://cloud.githubusercontent.com/assets/4635266/23270943/a01d22c0-f9c3-11e6-90ee-e2088e428bca.png)

**Comment by cpdcode** [comment]
@EthanDRaymond sales.sql --> I think I did it right but should be double checked before closing
