### ISSUE TITLE
Create Presentation

### ISSUE THREAD

**Issue by ryanabury** [ryanabury/CMPSC431W_SP17_Project#97]
We need to create and hopefully practice a 10 minute presentation that will be graded. We'll be presenting **Wednesday Evening (4/26)**.

**Comment by cpdcode** [comment]
What is the time and location of the presentation? Also, just to double check, this is different from the demo we have to do on **Friday @ 2:30 in 337 IST**, right?

**Comment by ryanabury** [comment]
Yes, it is different from the Demonstration we do on Friday. The presentations start tomorrow at 6:00 PM in 333 IST I believe (don't quote me on that though). As a result, we don't have class tomorrow morning, so we have more time to make sure our shit actually works! My plan was to have everyone create 2 slides on the challenges they faced and what they helped implement in the project as a whole and compile that into a 12 slide presentation (with an introduction and conclusion slide) and that should take about 10 minutes.
